module.exports = {
  "configs": {
    "1": {
      "name": "Caja Rural",
      "iban": "ES0530080238233583099621",
      "bic": "BCOEESMM008",
      "ccontable": "57200000001",
      "default": true,
      "banks": {
        "1": "Caja R. de Navarra, S.C.C."
      }
    },
    "2": {
      "name": "Santander",
      "iban": "ES4000494945202916254987",
      "bic": "BSCHESMMXXX",
      "ccontable": "52000000001",
      "default": false,
      "banks": {
        "2": "Banco Santander, S.A."
      }
    },
    "3": {
      "name": "Caixa",
      "iban": "ES7621009144320200048462",
      "bic": "CAIXESBBXXX",
      "ccontable": "57200000004",
      "default": false,
      "banks": {
        "3": "CaixaBank, S.A"
      }
    },
    "4": {
      "name": "Kutxabank",
      "iban": "ES6220950553509116660171",
      "bic": "BASKES2BXXX",
      "ccontable": "57200000000",
      "default": false,
      "banks": {
        "4": "Kutxabank, S.A."
      }
    }
  },
  "banks": {
    "14": "Banco Bilbao Vizcaya Argentaria, S.A.",
    "41": "Banco Santander, S.A.",
    "43": "Bankia, S.A.",
    "101": "Caja R. de Navarra, S.C.C.",
    "62": "CaixaBank, S.A",
    "168": "Kutxabank, S.A.",
    "1": "A\u0026G Banca Privada, S.A.",
    "2": null,
    "3": "Adyen B.V., S.E",
    "4": "AKF Bank Gmbh \u0026 Co Kg, S.E.",
    "5": "Allfunds Bank, S.A",
    "6": null,
    "7": "Aresbank. S.A.",
    "8": "Attijariwafa Bank Europe, S.E",
    "9": null,
    "10": "Banca March, S.A.",
    "11": "Banca Popolare Etica Sociedad Cooperativa Per Aziones, S.E.",
    "12": "Banca Pueyo, S.A.",
    "13": null,
    "15": "Banco Bpi, S.A., S.E.",
    "16": "Banco Caixa Geral, S.A.",
    "17": "Banco Caminos, S.A.",
    "18": "Banco Cetelem, S.A.",
    "19": null,
    "20": "Banco de Albacete, S.A.",
    "21": null,
    "22": "Banco de Castilla la Mancha, S.A.",
    "23": null,
    "24": null,
    "25": null,
    "26": null,
    "27": "Banco de Sabadell, S.A.",
    "28": "Banco do Brasil, AG., S.E",
    "29": "Banco Europeo de Finanzas, S.A.",
    "31": "Banco Finantia Sofinloc, S.A.",
    "32": "Banco Industrial de Bilbao, S.A.",
    "33": "Banco Inversis, S.A.",
    "34": "Banco Mediolanum, S.A.",
    "35": "Banco Occidental, S.A.",
    "36": "Banco Pastor, S.A",
    "37": null,
    "38": null,
    "39": null,
    "40": "Banco Primus, S.A., S.E.",
    "30": "Bancofar, S.A.",
    "42": "Bank Degroof Petercam Spain. S.A.",
    "46": "Bank of America Merrill Lynch International Limited",
    "44": "Bankinter, S.A.",
    "45": "Bankoa, S.A.",
    "47": "Banque Chaabi Du Maroc, S.E.",
    "48": null,
    "49": "Barclays Bank plc, S.E.",
    "50": "Bigbank AS Consumer Finance S.E.",
    "51": "Binckbank NV, S.E.",
    "52": "BMW Bank GMBH, SE",
    "54": null,
    "55": "BNP Paribas Factor, S.A., S.E.",
    "56": null,
    "57": "BNP Paribas Lease Group, S.A., S.E.",
    "58": "BNP Paribas Securities Services, S.E.",
    "53": "BNP Paribas, S.E.",
    "59": "CA Indosuez Wealth (Europe). S.E.",
    "60": null,
    "61": "Caixa Banco de Investimento, S.A., S.E.",
    "63": "Caixa de C. dels Enginyers-C.C. Ingenieros S.C.C.",
    "64": null,
    "65": "Caixa Popular-Caixa Rural, S.C.C.V.",
    "66": "Caixa R. Albalat Dels Sorells, C.C.V.",
    "67": "Caixa R. Altea, C.C.V.",
    "68": null,
    "69": null,
    "70": null,
    "71": "Caixa R. de L\u0027Alcudia, S.C.V.C.",
    "72": "Caixa R. de Turis, C.C.V.",
    "73": "Caixa R. Galega, S.C.C.L.G.",
    "74": "Caixa R. La Vall S. Isidro, S.C.C.V.",
    "75": "Caixa R. Les Coves de Vinroma, S.C.C.V.",
    "76": null,
    "77": "Caixa R. Sant Josep de Vilavella, S.C.C.V",
    "78": "Caixa Rural Torrent, C.C.V.",
    "79": null,
    "80": "Caja de Ahorros y M.P. de Ontinyent",
    "81": "Caja de Arquitectos, S.C.C.",
    "82": null,
    "83": "Caja Laboral Popular, C.C.",
    "85": null,
    "86": "Caja R. Central, S.C.C.",
    "87": "Caja R. de Albal, C.C.V.",
    "88": "Caja R. de Alginet, S.C.C.V.",
    "89": "Caja R. de Almendralejo, S.C.C.",
    "90": "Caja R. de Asturias, S.C.C.",
    "91": "Caja R. de Baena Ntra. Sra. de Guadalupe, S.C.C.A.",
    "92": null,
    "93": null,
    "94": "Caja R. de Castilla la Mancha, S.C.C",
    "95": "Caja R. de Cheste, S.C.C.",
    "96": "Caja R. de Extremadura, S.C.C.",
    "97": "Caja R. de Granada, S.C.C.",
    "98": "Caja R. de Guissona, S.C.C.",
    "99": null,
    "102": "Caja R. de Salamanca, S.C.C.",
    "103": "Caja R. de Soria, S.C.C.",
    "104": "Caja R. de Teruel, S.C.C.",
    "105": "Caja R. de Utrera, S.C.A.C.",
    "106": "Caja R. de Villamalea, S.C.C.A. de Castilla la Mancha",
    "107": "Caja R. de Villar, C.C.V.",
    "108": "Caja R. de Zamora, C.C.",
    "100": "Caja R. del Sur, S.C.C.",
    "109": "Caja R. la Junquera de Chilches, S.C.C.V.",
    "110": "Caja R. Ntra. Sra. la Esperanza de Onda, S.C.C.V.",
    "111": "Caja R. Nuestra Madre del Sol, S.C.A.C.",
    "112": "Caja R. Nueva Carteya. S.C.A.C",
    "114": "Caja R. S. Isidro de Vilafames, S.C.C.V.",
    "115": null,
    "116": null,
    "117": null,
    "118": null,
    "119": null,
    "120": "Caja R. S. Roque de Almenara S.C.C.V.",
    "113": null,
    "121": "Caja Rural de Albacete, Ciudad Real y Cuenca, SCC",
    "122": "Caja Rural de Aragon, Sociedad Cooperativa de Credito",
    "123": null,
    "124": null,
    "84": "Cajamar Caja Rural. S.C.C.",
    "125": "Cajasiete, Caja Rural, S.C.C.",
    "126": "Cajasur Banco, S.A",
    "127": "Cecabank, S.A.",
    "128": "China Construction Bank (Europe). S.A.. S.E",
    "129": null,
    "130": "Citibank Europe PLC. S.E",
    "131": "Claas Financial Services, S.A.S., S.E.",
    "132": "CM-CIC Bail. S.E.",
    "133": "CNH Capital Europe, S.A.S., S.E.",
    "134": "CNH Industrial Financial Services, S.E.",
    "135": "Cofidis, S.A., S.E.",
    "136": "Colonya - Caixa D\u0027Estalvis de Pollensa",
    "137": "Commerzbank Aktiengesellschaft, S.E.",
    "138": "Cooperatieve Rabobank U.A. S.E.",
    "139": "Credit Agricole Corporate and Investment Bank , S.E.",
    "140": "Credit Agricole Leasing \u0026 Factoring, S.E.",
    "141": null,
    "142": "Credit Suisse International, S.E",
    "143": "De Lage Landen International B.V., S.E.",
    "144": "Dell Bank International Designated Activity Company, S.E.",
    "146": "Deutsche Bank A.G., S.E.",
    "145": "Deutsche Bank, S.A.E.",
    "147": "Deutsche Pfandbriefbank Ag, S.E",
    "148": "Dexia Credit Local. S.E.",
    "149": "EBN Banco de Negocios, S.A.",
    "150": "Edmond de Rothschild (Europe), S.E.",
    "151": "Elavon Financial Services Limited Designated Activity Company. S.E.",
    "152": "Evo Banco S.A.",
    "153": "Fce Bank plc S.E.",
    "154": "Genefim, S.E.",
    "155": "Haitong Bank. S.A. S.E",
    "156": "Honda Bank GMBH, S.E.",
    "157": "HSBC Bank plc, S.E.",
    "158": "Ibercaja Banco, S.A.",
    "159": "Industrial and Commercial Bank of China (Europe),S.A.,S.E.",
    "160": "ING Bank, N.V. S.E",
    "161": null,
    "162": "Intesa Sanpaolo S.P.A., S.E.",
    "163": "J.P. Morgan International Bank Limited,S.E.",
    "164": "J.P.Morgan Securities PLC, S.E",
    "165": "John Deere Bank, S.A., S.E",
    "166": "Jpmorgan Chase Bank National Association, S.E.",
    "167": "KBL European Private Bankers S.A.,S.E.",
    "169": "Liberbank, S.A",
    "170": "Lombard Odier (Europe), S.A., S.E.",
    "171": "Mediobanca, S.E.",
    "172": "Mercedes-Benz Bank AG, S.E.",
    "173": "Mirabaud \u0026 CIE (Europe), S.A., S.E.",
    "174": "Mizuho Bank Europe N.V., S.E.",
    "175": "National Westminster Bank PLC, S.E.",
    "177": "Natixis Lease, S.A., S.E.",
    "176": "Natixis, S.A., S.E.",
    "178": "Novo Banco, S.A., S.E.",
    "179": "Nuevo Micro Bank, S.A",
    "180": "Open Bank, S.A.",
    "181": null,
    "182": "Pictet \u0026 Cie (Europe), S.A., S.E.",
    "183": "Popular Banca Privada, S.A.",
    "184": "Portigon AG, S.E.",
    "185": "RBC Europe Limited. S.E",
    "186": "RCI Banque, S.A., S.E.",
    "187": "RENTA 4 Banco, S.A.",
    "188": "Ruralnostra. S.C.C.Valenciana",
    "189": "Sabadell Consumer Finance, S.A.",
    "190": "Santander Consumer Finance, S.A.",
    "191": "Santander Investment, S.A.",
    "192": "Santander Securities Services,S.A.",
    "193": "Self Trade Bank, S.A.",
    "194": null,
    "195": "Sumitomo Mitsui Banking Corporation Europe Ltd., S.E.",
    "196": "Targobank, S.A.",
    "197": "The Bank of Tokyo-Mitsubishi UFJ, Ltd., S.E.",
    "198": "Toyota Kreditbank GMBH, S.E.",
    "199": "Triodos Bank, N.V., S.E.",
    "200": "UBS Europe. S.E.",
    "201": "Unicaja Banco, S.A.",
    "202": "Unicredit. S.P.A. S.E",
    "203": "Unione di Banche Italiane, S.p.a.,S.E.",
    "204": "Volkswagen Bank GmbH, S.E.",
    "205": "Wizink Bank. S.A.",
    "206": "Younited, S.E"
  },
  "id": null,
  "data": null,
  "data_banks": null,
  "error": [],
  "show_modify": false
}
